AWSTemplateFormatVersion: 2010-09-09
Description: Creates the Database of the System

Parameters:
  SubnetIds:
    Description: The array of the subnets where the RDS will be displayed
    Type: List<String>

  DBName:
    Type: String

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id

  MasterUsername:
    Type: String

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Jira Subnets
      DBSubnetGroupName: jira-subnetGroup
      SubnetIds:
        Ref: SubnetIds
      Tags:
        - Key: Name
          Value: JiraSubnetGroup

  KMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: Manual test KMS key
      EnableKeyRotation: True
      KeyPolicy:
        Version: '2012-10-17'
        Id: allow-root-account
        Statement:
          - Sid: AllowRootAccountFullAccess
            Effect: Allow
            Principal:
              AWS:
                Fn::Sub: arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow GitHub Actions to use KMS key,
            Effect: Allow,
            Principal:
              AWS: arn:aws:iam::926989967422:role/GithubActionsHarold
            Action:
              - kms:Encrypt,
              - kms:Decrypt,
              - kms:GenerateDataKey*,
              - kms:DescribeKey
            Resource: '*'

  DBInstance:
    DependsOn: KMSKey
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: 5
      BackupRetentionPeriod: 0
      DBInstanceClass: db.t3.micro
      DBName:
        Ref: DBName
      Engine: postgres
      MasterUsername:
        Ref: MasterUsername
      ManageMasterUserPassword: true
      MasterUserSecret:
        KmsKeyId:
          Ref: KMSKey
      VPCSecurityGroups:
        - Ref: RDSSecurityGroup
      DBSubnetGroupName:
        Ref: DBSubnetGroup
