AWSTemplateFormatVersion: 2010-09-09
Description: Creates the Database of the System

Parameters:
  SubnetIds:
    Description: The array of the subnets where the RDS will be displayed
    Type: List<String>

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Jira Subnets
      SubnetIds:
        - Ref: SubnetIds
    Tags:
      - Key: Name
        Value: JiraSubnetGroup
