AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for managing the security

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  Environment:
    Description: development | stage |production
    Type: String
    AllowedValues:
      - development
      - stage
      - production

Resources:
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: LoadBalancerSecurityGroup
      GroupDescription: LoadBalancerSecurityGroup
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          FromPort: 443
          ToPort: 443
          IpProtocol: tcp
      Tags:
        - Key: Name
          Value:
            Fn::Sub: Learning-Tracking-LoadBalancer-SG-{Environment}

  InstancesSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: InstancesSecurityGroup
      GroupDescription: InstancesSecurityGroup
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - SourceSecurityGroupId:
            Ref: LoadBalancerSecurityGroup
          FromPort: 32768
          ToPort: 65535
          IpProtocol: tcp
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value:
            Fn::Sub: Learning-Tracking-Instances-SG-{Environment}

  VpcEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: VpcEndpointSecurityGroup
      GroupDescription: VpcEndpointSecurityGroup
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - SourceSecurityGroupId:
            Ref: InstancesSecurityGroup
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
      Tags:
        - Key: Name
          Value:
            Fn::Sub: Learning-Tracking-Instances-SG-{Environment}

Outputs:
  VpcEndpointSecurityGroup:
    Value:
      Ref: VpcEndpointSecurityGroup
  LoadBalancerSecurityGroup:
    Value:
      Ref: LoadBalancerSecurityGroup
  InstancesSecurityGroup:
    Value:
      Ref: InstancesSecurityGroup
