name: Main orchestration of the Githubactions

on:
  push:
    branches:
      - dev_

permissions:
  id-token: write
  contents: read

jobs:
  deploy-s3-package-bucket-dev:
    name: Deploy the S3 Bucket package for the app
    if: (github.event_name == 'push' && contains(toJSON(github.event.head_commit.message), 'Merge branch ''stage'' into dev') == false)
    uses: ./.github/workflows/deploy_s3_package.yml
    with:
      environment: development
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}

  deploy-ecr-dev:
    needs: deploy-s3-package-bucket-dev
    name: Deploy the ECR infrastructure for the app
    if: (github.event_name == 'push' && contains(toJSON(github.event.head_commit.message), 'Merge branch ''stage'' into dev') == false)
    uses: ./.github/workflows/deploy_app.yml
    with:
      environment: development
    secrets:
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
