name: Run checks Tests Linting and build to ensure the application is ready to be deployed

on:
  pull_request:
    branches:
      - dev
      - stage
      - main
    paths-ignore:
      - './cloudformation/*'
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Cache Dependencies
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Run the linters
        run: npm run lint

  Build:
    needs: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache Dependencies
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Build the code
        run: npm run build
